image:
  size: [200, 150]
  spp: 100
scene:
  - {type: plane, normal: [+1, 0, 0], point: [-50, 0, 0], color: [0.75, 0.25, 0.25]}
  - {type: plane, normal: [-1, 0, 0], point: [+50, 0, 0], color: [0.25, 0.25, 0.75]}
  - {type: plane, normal: [0, 0, +1], point: [0, 0, 0], color: 0.75}
  - {type: plane, normal: [0, 0, -1], point: [0, 0, 225], color: [0.25, 0.75, 0.25]}
  - {type: plane, normal: [0, +1, 0], point: [0, 0, 0], color: 0.75}
  - {type: plane, normal: [0, -1, 0], point: [0, 100, 0], color: 0.75}
  - {type: sphere, radius: 16, center: [-25, 16, 25], color: 1, material: specular}
  - {type: sphere, radius: 12, center: [+25, 12, 50], color: 1, material: refraction}
  # - {type: sphere, radius: 600, center: [0, 699.7, 50], emission: 12}
  - {type: mesh, model: models/stanford/bun_zipper.ply, scale: 150, translate: [25, 19.05195, 50], color: 1, material: refraction, emission: [0.208, 0.172, 0.054]}
